name: embedded

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Build the Docker image
      run: |
           cd nginx-embeddedproxy
           docker build . --file dockerfile --tag jiladahe1997/nginx-embeddedproxy:latest
           docker login -u jiladahe1997 -p ${{secrets.dockerPassword}}
           docker push jiladahe1997/nginx-embeddedproxy:latest
